server:
  port: 8081
logging:
  level:
    org.example.springexample: debug
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create



